name: hw1_env
dependencies:
  - python=3.8
  - pip
  - pip:
    - numpy==1.20.2
    - pandas==1.2.4
    - scikit-learn==0.24.2
    - matplotlib==3.4.1
    - scipy==1.6.2
    - pickleshare==0.7.5